### ISSUE TITLE
FFHQH checkpoints link are broken

### ISSUE THREAD

**Issue by tomer196** [befozg/PHNet#14]
Hi,
Thanks for sharing your research.
I tried downloading the checkpoints but it seems that all the FFHQH checkpoints links are broken.
Can you fix them?

**Comment by hukenovs** [comment]
Hi.
Please, try again. We fixed short-links.

**Comment by tomer196** [comment]
Thank for the quick response, now it works.
Another question. Can I use the reained model on a different images size? say 1280*720

**Comment by hukenovs** [comment]
> Thank for the quick response, now it works. Another question. Can I use the reained model on a different images size? say 1280*720

Yes, you can preprocess (resize or/and pad) them to the input shape.
